### ISSUE TITLE
Integration can no longer be set up with HASS 2024.11.2

### ISSUE THREAD

**Issue by acardace** [petrleocompel/hikaxpro_hacs#140]
This is the error I get at startup:

```
Error setting up entry Hikvision_axpro_alarm.lan for hikvision_axpro

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_axpro/__init__.py", line 77, in async_setup_entry
    axpro = hikaxpro.HikAxPro(host, username, password, user_level=hikaxpro.USER_LEVEL_ADMIN_OPERATOR)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'hikaxpro' has no attribute 'USER_LEVEL_ADMIN_OPERATOR'
```

**Comment by petrleocompel** [comment]
Are you using some non-standard setup ? 

New version of underlying library was released and needs to be updated.

**Comment by acardace** [comment]
I had to to manually copy the new python library from /deps to /deps/lib/site-packages/... and now it works again.

Somehow the new library was getting placed inside /deps but the integration uses the one in /deps/lib, at this point I guess it's something related to my setup.

FYI, I use the official homeassistant image with the following kubernetes spec:

```
      containers:
        - image: ghcr.io/home-assistant/home-assistant:2024.11.2 # {"$imagepolicy": "apps:homeassistant"}
          name: homeassistant
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          ports:
            - containerPort: 8123
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            httpGet:
              port: 8123
              path: /manifest.json
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: false
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: TZ
              value: Europe/Rome
          volumeMounts:
            - mountPath: /config
              name: homeassistant-config
``` 

I don't think it's a non-standard setup but I don't know if it's the integration or homeassistant at fault here.

That said I'll close this issue but I'm not sure why it's not working.
