### ISSUE TITLE
Error setting up entry Hikvision_axpro_192.168.2.120 for hikvision_axpro after update V1.3.0 build 241205

### ISSUE THREAD

**Issue by latishev** [petrleocompel/hikaxpro_hacs#149]
AX Pro
Model DS-PWA96-M2H-WE
**Device Version V1.3.0 build 241205**

HAOS
Core 2024.12.5
Supervisor 2024.12.0
Operating System 14.1
Пользовательский интерфейс 20241127.8

Регистратор: homeassistant.config_entries
Источник: config_entries.py:640
Первое сообщение: 01:19:22 (4 сообщений)
Последнее сообщение: 01:38:25

Error setting up entry Hikvision_axpro_192.168.2.120 for hikvision_axpro
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_axpro/__init__.py", line 103, in async_setup_entry
    await hass.async_add_executor_job(coordinator.init_device)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hikvision_axpro/__init__.py", line 181, in init_device
    self.load_devices()
    ~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/hikvision_axpro/__init__.py", line 219, in load_devices
    devices = self._load_devices()
  File "/config/custom_components/hikvision_axpro/__init__.py", line 232, in _load_devices
    return ZonesConf.from_dict(response.json())
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_axpro/model.py", line 989, in from_dict
    list = from_list(ZoneConfListWrap.from_dict, obj.get("List"))
  File "/config/custom_components/hikvision_axpro/model.py", line 29, in from_list
    return [f(y) for y in x]
            ~^^^
  File "/config/custom_components/hikvision_axpro/model.py", line 973, in from_dict
    zone = ZoneConfig.from_dict(obj.get("Zone"))
  File "/config/custom_components/hikvision_axpro/model.py", line 718, in from_dict
    detector_type = DetectorType(obj.get("detectorType"))
  File "/usr/local/lib/python3.13/enum.py", line 722, in __call__
    return cls.__new__(cls, value)
           ~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/enum.py", line 1189, in __new__
    raise ve_exc
ValueError: 'motionDetector' is not a valid DetectorType

**Comment by petrleocompel** [comment]
I see the problem. It will be fixed in next beta release

**Comment by frapreviti** [comment]
same problem for me too

**Comment by petrleocompel** [comment]
Released as [v3.0.0-beta5](https://github.com/petrleocompel/hikaxpro_hacs/releases/tag/v3.0.0-beta5)

If you can please test and report back. 

Later it will be upstreamed to "master" and pushed to "stable" release of 3.0.0.
