### ISSUE TITLE
Areas as Separate Zones - Blocking call error

### ISSUE THREAD

**Issue by djb383** [petrleocompel/hikaxpro_hacs#32]
Hello,

When I enable the "Include areas as separate zones for arm/disarm", and I attempt to Arm or Disarm an area, I receive the following error:

> Blocking calls must be done in the executor or a separate thread; Use `await hass.async_add_executor_job()`; at custom_components/hikvision_axpro/__init__.py, line 255: response = self.axpro.makeRequest(endpoint, hikaxpro.consts.Method.PUT)

> Blocking calls must be done in the executor or a separate thread; Use `await hass.async_add_executor_job()`; at custom_components/hikvision_axpro/__init__.py, line 264: response = self.axpro.makeRequest(endpoint, hikaxpro.consts.Method.PUT) 

I do not get this problem when the "Include areas as separate zones for arm/disarm" is disabled.  The zone arms and disarms as expected.

<details><summary>More log details</summary>
<p>

2023-03-29 20:07:08.280 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to putrequest inside the event loop. This is causing stability issues. Please report issue to the custom integration author for hikvision_axpro doing blocking calls at custom_components/hikvision_axpro/__init__.py, line 255: response = self.axpro.makeRequest(endpoint, hikaxpro.consts.Method.PUT)

2023-03-29 20:07:08.281 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140043455650384] Blocking calls must be done in the executor or a separate thread; Use `await hass.async_add_executor_job()`; at custom_components/hikvision_axpro/__init__.py, line 255: response = self.axpro.makeRequest(endpoint, hikaxpro.consts.Method.PUT)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 726, in _handle_entity_call
    await result
  File "/config/custom_components/hikvision_axpro/alarm_control_panel.py", line 217, in async_alarm_arm_home
    await self.coordinator.async_arm_home(self.sys.id)
  File "/config/custom_components/hikvision_axpro/__init__.py", line 221, in async_arm_home
    is_success = await self.hass.async_add_executor_job(self._arm_home(sub_id=sub_id))
  File "/config/custom_components/hikvision_axpro/__init__.py", line 255, in _arm_home
    response = self.axpro.makeRequest(endpoint, hikaxpro.consts.Method.PUT)
  File "/usr/local/lib/python3.10/site-packages/hikaxpro.py", line 208, in makeRequest
    response = requests.put(endpoint, data=data, headers=headers)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1293, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 219, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 159, in protected_loop_func
    check_loop(func, strict=strict)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 146, in check_loop
    raise RuntimeError(

RuntimeError: Blocking calls must be done in the executor or a separate thread; Use `await hass.async_add_executor_job()`; at custom_components/hikvision_axpro/__init__.py, line 255: response = self.axpro.makeRequest(endpoint, hikaxpro.consts.Method.PUT)

</p>
</details> 

Thank you for your amazing work with this project!

**Comment by petrleocompel** [comment]
Also updates of areas were broken, it is now fixed.
