### ISSUE TITLE
AXhub features add request

### ISSUE THREAD

**Issue by youmax01** [petrleocompel/hikaxpro_hacs#36]
Hi!, is posible add in AXhub this features:

- Hikvision AXHub Wireless Output Expander DS-PM-WO8
- wireless siren list and atributes
- batterry
- comunication status

list of all things (json format)

 "ExDevStatus": {
            "OutputModList": [
                {
                    "OutputMod": {
                        "id": 1,
                        "seq": "Q00987842",
                        "status": "online",
                        "tamperEvident": false,
                        "charge": "normal",
                        "signal": 176
                    }
                },
                {
                    "OutputMod": {
                        "id": 2,
                        "seq": "",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "signal": 0
                    }
                },
                {
                    "OutputMod": {
                        "id": 3,
                        "seq": "",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "signal": 0
                    }
                },
                {
                    "OutputMod": {
                        "id": 4,
                        "seq": "",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "signal": 0
                    }
                }
            ],
            "OutputList": [
                {
                    "Output": {
                        "id": 0,
                        "name": "relay 1",
                        "status": "off",
                        "tamperEvident": false,
                        "charge": "normal",
                        "linkage": "manualCtrl",
                        "signal": 176
                    }
                },
                {
                    "Output": {
                        "id": 1,
                        "name": "relay 2",
                        "status": "off",
                        "tamperEvident": false,
                        "charge": "normal",
                        "linkage": "manualCtrl",
                        "signal": 176
                    }
                },
                {
                    "Output": {
                        "id": 2,
                        "name": "relay 3",
                        "status": "off",
                        "tamperEvident": false,
                        "charge": "normal",
                        "linkage": "manualCtrl",
                        "signal": 176
                    }
                },
                {
                    "Output": {
                        "id": 3,
                        "name": "relay 4",
                        "status": "off",
                        "tamperEvident": false,
                        "charge": "normal",
                        "linkage": "manualCtrl",
                        "signal": 176
                    }
                },
                {
                    "Output": {
                        "id": 4,
                        "name": "relay 5",
                        "status": "off",
                        "tamperEvident": false,
                        "charge": "normal",
                        "linkage": "manualCtrl",
                        "signal": 176
                    }
                },
                {
                    "Output": {
                        "id": 5,
                        "name": "relay 6",
                        "status": "off",
                        "tamperEvident": false,
                        "charge": "normal",
                        "linkage": "manualCtrl",
                        "signal": 176
                    }
                },
                {
                    "Output": {
                        "id": 6,
                        "name": "relay 7",
                        "status": "off",
                        "tamperEvident": false,
                        "charge": "normal",
                        "linkage": "manualCtrl",
                        "signal": 176
                    }
                },
                {
                    "Output": {
                        "id": 7,
                        "name": "relay 8",
                        "status": "off",
                        "tamperEvident": false,
                        "charge": "normal",
                        "linkage": "manualCtrl",
                        "signal": 176
                    }
                },
                {
                    "Output": {
                        "id": 8,
                        "name": "relay 9",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 9,
                        "name": "relay 10",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 10,
                        "name": "relay 11",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 11,
                        "name": "relay 12",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 12,
                        "name": "relay 13",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 13,
                        "name": "relay 14",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 14,
                        "name": "relay 15",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 15,
                        "name": "relay 16",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 16,
                        "name": "relay 17",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 17,
                        "name": "relay 18",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 18,
                        "name": "relay 19",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 19,
                        "name": "relay 20",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 20,
                        "name": "relay 21",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 21,
                        "name": "relay 22",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 22,
                        "name": "relay 23",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 23,
                        "name": "relay 24",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 24,
                        "name": "relay 25",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 25,
                        "name": "relay 26",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 26,
                        "name": "relay 27",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 27,
                        "name": "relay 28",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 28,
                        "name": "relay 29",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 29,
                        "name": "relay 30",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 30,
                        "name": "relay 31",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                },
                {
                    "Output": {
                        "id": 31,
                        "name": "relay 32",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "linkage": "manualCtrl",
                        "signal": 0
                    }
                }
            ],
            "SirenList": [
                {
                    "Siren": {
                        "id": 1,
                        "name": "Sirena interna",
                        "seq": "Q01151860",
                        "status": "off",
                        "tamperEvident": false,
                        "charge": "normal",
                        "signal": 152
                    }
                },
                {
                    "Siren": {
                        "id": 2,
                        "name": "sirena externa",
                        "seq": "",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "signal": 0
                    }
                },
                {
                    "Siren": {
                        "id": 3,
                        "name": "Sirena vía radio 3",
                        "seq": "",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "signal": 0
                    }
                },
                {
                    "Siren": {
                        "id": 4,
                        "name": "Sirena vía radio 4",
                        "seq": "",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "signal": 0
                    }
                }
            ],
            "RepeaterList": [
                {
                    "Repeater": {
                        "id": 1,
                        "name": "repeater 1",
                        "seq": "",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "signal": 0
                    }
                },
                {
                    "Repeater": {
                        "id": 2,
                        "name": "repeater 2",
                        "seq": "",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "signal": 0
                    }
                }
            ],
            "CardReaderList": [
                {
                    "CardReader": {
                        "id": 1,
                        "seq": "",
                        "name": "Lector de tarjetas 1",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "signal": 0
                    }
                },
                {
                    "CardReader": {
                        "id": 2,
                        "seq": "",
                        "name": "Lector de tarjetas 2",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "signal": 0
                    }
                },
                {
                    "CardReader": {
                        "id": 3,
                        "seq": "",
                        "name": "Lector de tarjetas 3",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "signal": 0
                    }
                },
                {
                    "CardReader": {
                        "id": 4,
                        "seq": "",
                        "name": "Lector de tarjetas 4",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "signal": 0
                    }
                }
            ],
            "KeypadList": [
                {
                    "Keypad": {
                        "id": 1,
                        "seq": "Q00987589",
                        "name": "Teclado ingreso",
                        "status": "online",
                        "tamperEvident": false,
                        "charge": "normal",
                        "signal": 147
                    }
                },
                {
                    "Keypad": {
                        "id": 2,
                        "seq": "",
                        "name": "Teclado 2",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "signal": 0
                    }
                },
                {
                    "Keypad": {
                        "id": 3,
                        "seq": "",
                        "name": "Teclado 3",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "signal": 0
                    }
                },
                {
                    "Keypad": {
                        "id": 4,
                        "seq": "",
                        "name": "Teclado 4",
                        "status": "notRelated",
                        "tamperEvident": false,
                        "signal": 0
                    }
                }
            ]
        },
        "BatteryList": [
            {
                "Battery": {
                    "id": 1,
                    "status": "normal",
                    "percent": 100,
                    "voltage": 4
                }
            }
        ],
        "CommuniStatus": {
            "wired": "break",
            "wifi": "normal",
            "wifiSignal": 4,
            "mobile": "normal",
            "mobileSignal": 2,
            "flow": 0.0,
            "monFlowLimit": 100,
            "cloud": "normal"
        }
    }
}

**Comment by youmax01** [comment]
> The problem currently was found. ISAPI spec - AX Pro sends info about device in status. But AX Hub only in configuration read out. So my proposal is to load configuration on start. Persist it and use only the status later.

perfect! thanks

**Comment by nautilus7** [comment]
Hi, have you made any progress on this? Is there anything you need to test?

**Comment by petrleocompel** [comment]
I started some progress of new "configration load" in DEV branch, but i am not yet done. Sadly not many productive days... 

I will notify on release correct issues.

**Comment by petrleocompel** [comment]
For those who wants to live on "edge" there is beta release (`v2.0.0-beta2`)[https://github.com/petrleocompel/hikaxpro_hacs/releases/tag/v2.0.0-beta2]

You can report back. It is not 100% tested. But that is "life on the edge".

**Comment by youmax01** [comment]
thanks you for the great job!!!, i will try

**Comment by petrleocompel** [comment]
@youmax01 I released another beta with fixed this issue [beta4](https://github.com/petrleocompel/hikaxpro_hacs/releases/tag/v2.0.0-beta4)

**Comment by youmax01** [comment]
> @youmax01 I released another beta with fixed this issue [beta4](https://github.com/petrleocompel/hikaxpro_hacs/releases/tag/v2.0.0-beta4)

Thanks , again, in beta 5 with or without AXhub API check:

Error setting up entry Hikvision_axpro_192.168.1.4 for hikvision_axpro
07:08:31 – (ERROR) hikvision_axpro (integración personalizada) - el mensaje se produjo por primera vez a las 07:06:16 y aparece 2 veces
Debug data <SessionLoginCap version="2.0" xmlns="http://www.hikvision.com/ver20/XMLSchema"> <sessionID>872c3962a8eabca85842</sessionID> <challenge>26b6e53830934824588aba88f0798b36</challenge> <iterations>100</iterations> <isSupportRTSPWithSession>true</isSupportRTSPWithSession> </SessionLoginCap>
07:06:15 – (ADVERTENCIA) hikvision_axpro (integración personalizada)

**Comment by petrleocompel** [comment]
@youmax01 No more info ? The log does not say anything.

**Comment by youmax01** [comment]
> @youmax01 No more info ? The log does not say anything.

yes, sorry, my bad:

2023-05-11 09:08:11.831 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Hikvision_axpro_192.168.1.4 for hikvision_axpro
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hikvision_axpro/__init__.py", line 105, in async_setup_entry
    await hass.async_add_executor_job(coordinator.init_device)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hikvision_axpro/__init__.py", line 177, in init_device
    self.load_devices()
  File "/config/custom_components/hikvision_axpro/__init__.py", line 181, in load_devices
    devices = self._load_devices()
  File "/config/custom_components/hikvision_axpro/__init__.py", line 194, in _load_devices
    return ZonesConf.from_dict(response.json())
  File "/config/custom_components/hikvision_axpro/model.py", line 834, in from_dict
    list = from_list(ListElement.from_dict, obj.get("List"))
  File "/config/custom_components/hikvision_axpro/model.py", line 29, in from_list
    return [f(y) for y in x]
  File "/config/custom_components/hikvision_axpro/model.py", line 29, in <listcomp>
    return [f(y) for y in x]
  File "/config/custom_components/hikvision_axpro/model.py", line 818, in from_dict
    zone = ZoneConfig.from_dict(obj.get("Zone"))
  File "/config/custom_components/hikvision_axpro/model.py", line 662, in from_dict
    linkage_sub_system = from_list(from_int, obj.get("linkageSubSystem"))
  File "/config/custom_components/hikvision_axpro/model.py", line 28, in from_list
    assert isinstance(x, list)

**Comment by nautilus7** [comment]
I get same error with beta5. It cannot setup the integration with ax hub.

**Comment by petrleocompel** [comment]
@nautilus7 @youmax01 
[beta6](https://github.com/petrleocompel/hikaxpro_hacs/releases/tag/v2.0.0-beta6) with more fixes. Went throught possible outputs we will see.

**Comment by youmax01** [comment]
> @nautilus7 @youmax01 [beta6](https://github.com/petrleocompel/hikaxpro_hacs/releases/tag/v2.0.0-beta6) with more fixes. Went throught possible outputs we will see.
beta 6 work ok, but dont show new AXhub info

![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/35151341/60d1343b-0158-45e9-9ea5-ed871b1a3d86)

in sensors see new items

![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/35151341/0d436a56-873a-4867-b55b-d4f5095afb6f)

**Comment by petrleocompel** [comment]
Okay. Finally seems your setup works. Battery is again different endpoint. And currently not called. But we know what type of device is returned from status.

**Comment by nautilus7** [comment]
Failed when arming...

```
2023-05-12 17:53:49.032 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140344842295888] Unexpected response status code 400 returned with message { "statusCode": 4, "statusString": "Invalid Operation", "subStatusCode": "arming", "errorCode": 1073774621, "errorMsg": "arming" }
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 216, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 977, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/config/custom_components/hikvision_axpro/alarm_control_panel.py", line 124, in async_alarm_arm_away
    await self.coordinator.async_arm_away()
  File "/config/custom_components/hikvision_axpro/__init__.py", line 264, in async_arm_away
    is_success = await self.hass.async_add_executor_job(self.axpro.arm_away)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hikvision_axpro/hikax/hikax.py", line 164, in arm_away
    return self._base_json_request(f"http://{self.host}{consts.Endpoints.Alarm_ArmAway.replace('{}', sid)}",
  File "/config/custom_components/hikvision_axpro/hikax/hikax.py", line 153, in _base_json_request
    raise errors.UnexpectedResponseCodeError(response.status_code, response.text)
errors.errors.UnexpectedResponseCodeError: Unexpected response status code 400 returned with message { "statusCode": 4, "statusString": "Invalid Operation", "subStatusCode": "arming", "errorCode": 1073774621, "errorMsg": "arming" }
```

**Comment by petrleocompel** [comment]
@nautilus7  Are talking about version beta6 ? 
Please can you try without AXHub checkbox (restart HA after configuring) ? In beta version i am currently moving away from the AXHub checkbox to standartize this with AXPro API. So no differences between devices will later occur.

**Comment by petrleocompel** [comment]
Also please make sure for AXHub to not provide "core for arming". Keep it empty.

**Comment by nautilus7** [comment]
Yes, beta 6. Unchecked the AXHub api, but still doesn't work (arm/disarm). It doesn't throw an error though, unfortunately.

**Comment by youmax01** [comment]
ARM and DISARM work perfect for me in beta6

![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/35151341/c9ffb45e-be86-4424-ac0d-48452cf4ed72)

**Comment by nautilus7** [comment]
Ok, might be doing something wrong. Will check again later.

Which home assistant version do you use? Is that the new alarm card introduced recently?

**Comment by petrleocompel** [comment]
It can be still integration problem. Please both of you post answers 

Is it AXHub device?
PIN is empty?
AXHub checkbox status?
Any errors after inicialization?

@nautilus7 You can always revert back to v1.

**Comment by youmax01** [comment]
> It can be still integration problem. Please both of you post answers
> 
> Is it AXHub device? PIN is empty? AXHub checkbox status? Any errors after inicialization?
> 
> @nautilus7 You can always revert back to v1.

AXhub
PIN not empty
AXhub check
lastest HA version

![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/35151341/4766c4ed-42b1-4b89-8d29-ed1ea56ed0cf)

**Comment by nautilus7** [comment]
Yes, simple AX Hub, not pro. Not errors, apart from those already posted in https://github.com/petrleocompel/hikaxpro_hacs/issues/36#issuecomment-1545705800

![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/1540233/a2a2b92e-e891-4bb0-a53a-bb7cfba26e88)

**Comment by nautilus7** [comment]
It seems that it was some error from my side. I am able to arm/disarm the system just fine. Sorry for the false... alarm.

I'll test the newer betas soon and report back. Thanks

**Comment by petrleocompel** [comment]
If any feedback will be for v2 beta please post it to #41. Also last version is beta8.

**Comment by nautilus7** [comment]
@petrleocompel hi, haven't used home assistant and this integration for a long time, but now started fiddling around it again.

What's the current development status of it? There are some long standing issues with the ax hub (not the pro) like arming errors, magnet sensors and PIR detectors not being detected properly as such and various properties of these devices, like magnet presence and battery level not displaying.

Can we hope in any updates/fixes in the future? Regards.

**Comment by petrleocompel** [comment]
As the main page of project states. Parts are implemented. 

It is currently pull based integration and since no new discovery was made with some event streaming from the device side we cannot implement "event reaction".
(Like pir sensor trigger)

I am still working on it in my free time. And also on the underlaying python lib. Fixing critical bugs and reacting to messages in shortest possible terms. 

As I am pointing out I do it in my free time. Sadly other projects are having higher priority lately. So no I was not working on new implementations just maintenance. I have worked on the siren implementation but not pushed any beta version yet. 

And also refactoring for deprecations are in my git stash.

**Comment by petrleocompel** [comment]
@nautilus7 More to your question.. In github issues you can see a lot of "questions" or "invalid" tags. 
Also lot of issues seems stale but most it is because of response from the users. 
I do not want to close the issues if they are unsolved but without more info I often cannot proceed.

If they are passed to "dev phase" they are marked with "feature" and etc...

You can always help point out some stuff and report and help with testing and etc... 

<details>
  <summary>Personal rant - click to see (not important)</summary>

Sadly also a part of these issues is not being correctly used... People does not read `README.md` , does not do pre-flight check of the system. And then making and Issue that something does not work often without logs and info about version of the integration, version of the device and more...

It is very demotivating to argue with strangers on internet about stuff you do in your free time and be a detective for them "questioning" them if their system is correctly configured and if their system has only one user... in the end finding out that they we not telling you the truth... :face_exhaling: 

</details>

**Comment by nautilus7** [comment]
I know exactly what you're saying. I have been there, being a developer as well.

I haven't used home assistant for some time, that's why what's why I asked for the current status of development, because I remember saying quite a few times that you do not have much free time.

Some time ago (I believe 2 years) we had a live session with you running postman on my pc and you were able to fix some issues with the ax hub. I wonder if we can do the same again in when you have time. I can make sure I have correctly setup my system and provide you all logs I can find. Then you can run your test directly on my system to find the missing bits.

Let me know if you can do this.

**Comment by petrleocompel** [comment]
@nautilus7 any troubles with using it again ? Just hit me up by email to get in touch. We can give it a try. 
We will have to find out a date since I will be soon traveling to different continent but we will figure it out.

**Comment by petrleocompel** [comment]
**v3.2.0** adds AX Hub-oriented peripherals from `exDevStatus`:

- Output expander / extension module status
- Wireless/external siren sensors (+ optional control when supported)
- Keypad / repeater diagnostics
- Hub battery / AC / host status polls

Please upgrade to **v3.2.0** and reopen (or file a focused issue) for any remaining gap.
