### ISSUE TITLE
problema after last update V 2.0. beta

### ISSUE THREAD

**Issue by wifi75** [petrleocompel/hikaxpro_hacs#39]
hello after update the integration not working:

![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/31816231/f8ff5aa9-ba5b-4a37-b63d-6262a9522c51)

see below

```
Logger: homeassistant.config_entries
Source: custom_components/hikvision_axpro/model.py:43
Integration: hikvision_axpro
First occurred: 09:15:31 (2 occurrences)
Last logged: 09:48:24

Error setting up entry Hikvision_axpro_192.168.1.17 for hikvision_axpro
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hikvision_axpro/__init__.py", line 105, in async_setup_entry
    await hass.async_add_executor_job(coordinator.init_device)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hikvision_axpro/__init__.py", line 177, in init_device
    self.load_devices()
  File "/config/custom_components/hikvision_axpro/__init__.py", line 181, in load_devices
    devices = self._load_devices()
  File "/config/custom_components/hikvision_axpro/__init__.py", line 194, in _load_devices
    return ZonesConf.from_dict(response.json())
  File "/config/custom_components/hikvision_axpro/model.py", line 803, in from_dict
    list = from_list(ListElement.from_dict, obj.get("List"))
  File "/config/custom_components/hikvision_axpro/model.py", line 29, in from_list
    return [f(y) for y in x]
  File "/config/custom_components/hikvision_axpro/model.py", line 29, in <listcomp>
    return [f(y) for y in x]
  File "/config/custom_components/hikvision_axpro/model.py", line 787, in from_dict
    zone = ZoneConfig.from_dict(obj.get("Zone"))
  File "/config/custom_components/hikvision_axpro/model.py", line 675, in from_dict
    related_chan_list = from_list(RelatedChanList.from_dict, obj.get("RelatedChanList"))
  File "/config/custom_components/hikvision_axpro/model.py", line 29, in from_list
    return [f(y) for y in x]
  File "/config/custom_components/hikvision_axpro/model.py", line 29, in <listcomp>
    return [f(y) for y in x]
  File "/config/custom_components/hikvision_axpro/model.py", line 553, in from_dict
    related_chan = RelatedChan.from_dict(obj.get("RelatedChan"))
  File "/config/custom_components/hikvision_axpro/model.py", line 533, in from_dict
    relator = from_union([Relator, from_none], obj.get("relator"))
  File "/config/custom_components/hikvision_axpro/model.py", line 43, in from_union
    assert False
AssertionError
```

**Comment by petrleocompel** [comment]
fixed in [`v2.0.0-beta3`](https://github.com/petrleocompel/hikaxpro_hacs/releases/tag/v2.0.0-beta3)

**Comment by leciuk81** [comment]
For me beta 3 doesn't work either, same problem. Even going back to the previous version it doesn't work anymore.
![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/126766794/73f72a48-0b3c-417d-8bb9-f460fb9cd187)
`Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.hikvision_axpro.config_flow
Source: custom_components/hikvision_axpro/hikax/hikax.py:77
Integration: hikvision_axpro
First occurred: 14:33:51 (1 occurrences)
Last logged: 14:33:51

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/hikvision_axpro/config_flow.py", line 218, in async_step_init
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/hikvision_axpro/config_flow.py", line 151, in validate_input
    if not await hub.authenticate():
  File "/config/custom_components/hikvision_axpro/config_flow.py", line 116, in authenticate
    is_connect_success = await self.hass.async_add_executor_job(self.axpro.connect)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hikvision_axpro/hikax/hikax.py", line 95, in connect
    encoded_password = self.encode_password(params)
  File "/config/custom_components/hikvision_axpro/hikax/hikax.py", line 77, in encode_password
    if session_cap.isIrreversible:
AttributeError: 'SessionLoginCap' object has no attribute 'isIrreversible'
`

`Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.hikvision_axpro.hikax.hikax
Source: custom_components/hikvision_axpro/hikax/hikax.py:93
Integration: hikvision_axpro
First occurred: 14:33:51 (1 occurrences)
Last logged: 14:33:51

Debug data <SessionLoginCap version="2.0" xmlns="http://www.hikvision.com/ver20/XMLSchema"> <sessionID>1bb71a2144a4c759cd79f4295f007ec0a57ce5e45b668962c9eb076aee97eca3</sessionID> <challenge>f2afb9aa54826f142a6b314a769aeff8</challenge> <iterations>100</iterations> <isSupportRTSPWithSession>true</isSupportRTSPWithSession> <isIrreversible>true</isIrreversible> <sessionIDVersion>2.1</sessionIDVersion> <salt>3519F0AB7181690F20D90DCCC9EC9239577C5FA5C213048AED81B2AB3BBA8C8E</salt> <salt2>894FC272840644114F489CCBCABFB7BED9F97226E2528C021ABD0321AB6D3421</salt2> </SessionLoginCap>`

**Comment by petrleocompel** [comment]
Are you using AXHub api or not ? in configuration the checkbox. I think you do. Please try to untick this box. And restart HA.

**Comment by petrleocompel** [comment]
This AXHub API lib will be deleted because I finally have access to the PyPi package for AXPro api.

**Comment by leciuk81** [comment]
It had activated.
Disabled restarted but it doesn't work either.
I also tried uninstalling and reinstalling.
It does not work

![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/126766794/51aaded9-17d3-4e59-80c5-536648ff0093)

![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/126766794/515d9f10-bb11-48ac-bb25-9fbb041bd391)

![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/126766794/fe11566c-4966-40ba-9a1b-9bdd69b6eccd)

`Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: homeassistant.config_entries
Source: custom_components/hikvision_axpro/model.py:18
Integration: hikvision_axpro
First occurred: 14:58:51 (1 occurrences)
Last logged: 14:58:51

Error setting up entry Hikvision_axpro_192.168.10.107 for hikvision_axpro
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hikvision_axpro/__init__.py", line 105, in async_setup_entry
    await hass.async_add_executor_job(coordinator.init_device)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hikvision_axpro/__init__.py", line 177, in init_device
    self.load_devices()
  File "/config/custom_components/hikvision_axpro/__init__.py", line 181, in load_devices
    devices = self._load_devices()
  File "/config/custom_components/hikvision_axpro/__init__.py", line 194, in _load_devices
    return ZonesConf.from_dict(response.json())
  File "/config/custom_components/hikvision_axpro/model.py", line 832, in from_dict
    list = from_list(ListElement.from_dict, obj.get("List"))
  File "/config/custom_components/hikvision_axpro/model.py", line 29, in from_list
    return [f(y) for y in x]
  File "/config/custom_components/hikvision_axpro/model.py", line 29, in <listcomp>
    return [f(y) for y in x]
  File "/config/custom_components/hikvision_axpro/model.py", line 816, in from_dict
    zone = ZoneConfig.from_dict(obj.get("Zone"))
  File "/config/custom_components/hikvision_axpro/model.py", line 679, in from_dict
    relate_detector = from_bool(obj.get("relateDetector"))
  File "/config/custom_components/hikvision_axpro/model.py", line 18, in from_bool
    assert isinstance(x, bool)
AssertionError
`

`Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.hikvision_axpro.model
Source: custom_components/hikvision_axpro/model.py:832
Integration: hikvision_axpro
First occurred: 14:58:51 (2 occurrences)
Last logged: 14:58:51

Invalid zone chime_warning_type None
Zone conf: {'id': 1, 'zoneName': 'Rilevatore presenza stanzetta (zona 2)', 'detectorType': 'passiveInfraredDetector', 'zoneType': 'Instant', 'subSystemNo': 1, 'linkageSubSystem': [1], 'supportLinkageSubSystemList': [1, 2, 3, 4], 'enterDelay': 30, 'exitDelay': 30, 'stayArmDelayTime': 30, 'sirenDelayTime': 0, 'stayAwayEnabled': True, 'chimeEnabled': False, 'silentEnabled': False, 'chimeWarningType': 'continuous', 'timeoutType': 'recover', 'timeout': 30, 'relateDetector': True, 'detectorSeq': 'Q06554496', 'RelatedChanList': [{'RelatedChan': {'relator': 'app', 'cameraSeq': 'F36046086', 'relatedChan': 1, 'linkageCameraName': 'Cucina'}}], 'doubleKnockEnabled': False, 'doubleKnockTime': 5, 'CrossZoneCfg': {'isAssociated': False, 'supportAssociatedZone': [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'alreadyAssociatedZone': [], 'supportLinkageChannelID': [1, 2, 3, 4, 5, 6, 7, 9, 10], 'alreadyLinkageChannelID': [], 'associateTime': 1800}, 'newKeyZoneTriggerTypeCfg': 'zoneStatus', 'zoneStatusCfg': 'triggerArm', 'armNoBypassEnabled': False, 'RelatedPIRCAM': {'supportLinkageZones': [14], 'linkageZone': [], 'linkagePIRCAMName': ''}, 'armMode': 'and', 'zoneAttrib': 'wireless'}`

**Comment by petrleocompel** [comment]
@leciuk81 [beta5](https://github.com/petrleocompel/hikaxpro_hacs/releases/tag/v2.0.0-beta5) just landed with this fix. Maybe another rotation would be needed before i will remake the models.
