### ISSUE TITLE
v2 - beta feedback

### ISSUE THREAD

**Issue by petrleocompel** [petrleocompel/hikaxpro_hacs#41]
It seems `v2.0.0-beta8` is stable enough. If no feedback with errors will be provided this week i will release it on Friday 19th May. 

Please post feedback in this post. If currently any problems are present.

**Comment by youmax01** [comment]
work perfect with beta8 in AXhub, no errors

**Comment by wifi75** [comment]
hello also beta 8 not working:

see log below

```
ogger: homeassistant.config_entries
Source: custom_components/hikvision_axpro/__init__.py:89
Integration: hikvision_axpro
First occurred: 08:08:10 (2 occurrences)
Last logged: 08:13:01

Error setting up entry Hikvision_axpro_192.168.1.17 for hikvision_axpro
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb17582d0c0>: Failed to establish a new connection: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.17', port=80): Max retries exceeded with url: /ISAPI/System/Network/interfaces (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb17582d0c0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hikvision_axpro/__init__.py", line 89, in async_setup_entry
    mac = await hass.async_add_executor_job(axpro.get_interface_mac_address, 1)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hikaxpro.py", line 235, in get_interface_mac_address
    response = self.make_request(endpoint, consts.Method.GET)
  File "/usr/local/lib/python3.10/site-packages/hikaxpro.py", line 274, in make_request
    response = requests.get(endpoint, headers=headers)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.17', port=80): Max retries exceeded with url: /ISAPI/System/Network/interfaces (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb17582d0c0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

```

**Comment by petrleocompel** [comment]
@nautilus7 
1. I will have to investigate a little bit. Might not get that info from AXHub
2. The break down - means there is fault. I guess this is something from AXHub. Not sure if AXPro has it same. I dont think it is really a problem.

**Comment by youmax01** [comment]
> @nautilus7
> 
> 1. I will have to investigate a little bit. Might not get that info from AXHub
> 2. The break down - means there is fault. I guess this is something from AXHub. Not sure if AXPro has it same. I dont think it is really a problem.

The break down apears when sensor is open, when sensor is close change to online. dont know why.
![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/35151341/f798169d-6be6-4bc6-a6d4-52ae4a2520e2)

**Comment by leciuk81** [comment]
HI,
for me always the same errors for all Beta versions. Also now I can no longer install version 1.3.1 which worked for me.
Below is the error received.
Hope you can fix it.
Thank you

![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/126766794/580118f9-0e33-40c1-8227-b00c400b714c)

![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/126766794/8935237e-1c25-4cce-8d6b-0d2d285dfaaf)

![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/126766794/983ecf07-f7c6-45fe-80b3-34b0b8e5a780)

`Logger: homeassistant.config_entries
Source: custom_components/hikvision_axpro/model.py:662
Integration: hikvision_axpro
First occurred: 11:19:59 (2 occurrences)
Last logged: 11:20:53

Error setting up entry Hikvision_axpro_192.168.10.107 for hikvision_axpro
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hikvision_axpro/__init__.py", line 105, in async_setup_entry
    await hass.async_add_executor_job(coordinator.init_device)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hikvision_axpro/__init__.py", line 177, in init_device
    self.load_devices()
  File "/config/custom_components/hikvision_axpro/__init__.py", line 181, in load_devices
    devices = self._load_devices()
  File "/config/custom_components/hikvision_axpro/__init__.py", line 194, in _load_devices
    return ZonesConf.from_dict(response.json())
  File "/config/custom_components/hikvision_axpro/model.py", line 822, in from_dict
    list = from_list(ListElement.from_dict, obj.get("List"))
  File "/config/custom_components/hikvision_axpro/model.py", line 29, in from_list
    return [f(y) for y in x]
  File "/config/custom_components/hikvision_axpro/model.py", line 29, in <listcomp>
    return [f(y) for y in x]
  File "/config/custom_components/hikvision_axpro/model.py", line 806, in from_dict
    zone = ZoneConfig.from_dict(obj.get("Zone"))
  File "/config/custom_components/hikvision_axpro/model.py", line 662, in from_dict
    chime_warning_type = ChimeWarningType(obj.get("chimeWarningType"))
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'continuous' is not a valid ChimeWarningType`

After some time added more errors

![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/126766794/4c6344b8-3bb8-468c-a820-881d58b6b311)

`Logger: custom_components.hikvision_axpro.hikax.hikax
Source: custom_components/hikvision_axpro/hikax/hikax.py:208
Integration: hikvision_axpro
First occurred: 11:28:59 (1 occurrences)
Last logged: 11:28:59

Debug data <SessionLoginCap version="2.0" xmlns="http://www.hikvision.com/ver20/XMLSchema"> <sessionID>7936be44ebdaef3efcb443785042c2be917999626e4948284d66867552681190</sessionID> <challenge>e47a993acf5b7fd7b253fbb4f7ef3624</challenge> <iterations>100</iterations> <isSupportRTSPWithSession>true</isSupportRTSPWithSession> <isIrreversible>true</isIrreversible> <sessionIDVersion>2.1</sessionIDVersion> <salt>3519F0AB7181690F20D90DCCC9EC9239577C5FA5C213048AED81B2AB3BBA8C8E</salt> <salt2>894FC272840644114F489CCBCABFB7BED9F97226E2528C021ABD0321AB6D3421</salt2> </SessionLoginCap>`

`Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.hikvision_axpro.hikax.hikax
Source: custom_components/hikvision_axpro/hikax/hikax.py:93
Integration: hikvision_axpro
First occurred: 11:28:53 (1 occurrences)
Last logged: 11:28:53

Debug data <SessionLoginCap version="2.0" xmlns="http://www.hikvision.com/ver20/XMLSchema"> <sessionID>da1d7a578ee5aa63ddf592894a0d06469e83029fc8977bff7dcf24c8982de3b3</sessionID> <challenge>29d7dac5170e32c2888ce93de3c2dc43</challenge> <iterations>100</iterations> <isSupportRTSPWithSession>true</isSupportRTSPWithSession> <isIrreversible>true</isIrreversible> <sessionIDVersion>2.1</sessionIDVersion> <salt>3519F0AB7181690F20D90DCCC9EC9239577C5FA5C213048AED81B2AB3BBA8C8E</salt> <salt2>894FC272840644114F489CCBCABFB7BED9F97226E2528C021ABD0321AB6D3421</salt2> </SessionLoginCap>`

**Comment by petrleocompel** [comment]
**Beta9** - Released

**Comment by petrleocompel** [comment]
@leciuk81 Any feedback on beta9 ? changes ? works?

**Comment by leciuk81** [comment]
Hello, with Beta 9 it started working fine again.

**Comment by petrleocompel** [comment]
Version 2.0.0-beta16 was released.
If there will be no issues until end of this week version 2 will be released as stable.

**Comment by petrleocompel** [comment]
No issues found over beta 2. It is going to be released today.

**Comment by petrleocompel** [comment]
Version 2.0.0 released to public
