### ISSUE TITLE
Missing detector type

### ISSUE THREAD

**Issue by alejodeantoni** [petrleocompel/hikaxpro_hacs#47]
Heyy hello I just updated HA to latest version and I lost control of AX pro I'm getting the following error

Este error se originó a partir de una integración personalizada.

Logger: homeassistant.config_entries
Source: custom_components/hikvision_axpro/model.py:660
Integration: hikvision_axpro
First occurred: 18:51:44 (2 occurrences)
Last logged: 18:56:44

```
Error setting up entry Hikvision_axpro_192.168.0.128 for hikvision_axpro
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hikvision_axpro/__init__.py", line 105, in async_setup_entry
    await hass.async_add_executor_job(coordinator.init_device)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hikvision_axpro/__init__.py", line 177, in init_device
    self.load_devices()
  File "/config/custom_components/hikvision_axpro/__init__.py", line 181, in load_devices
    devices = self._load_devices()
  File "/config/custom_components/hikvision_axpro/__init__.py", line 194, in _load_devices
    return ZonesConf.from_dict(response.json())
  File "/config/custom_components/hikvision_axpro/model.py", line 833, in from_dict
    list = from_list(ListElement.from_dict, obj.get("List"))
  File "/config/custom_components/hikvision_axpro/model.py", line 29, in from_list
    return [f(y) for y in x]
  File "/config/custom_components/hikvision_axpro/model.py", line 29, in <listcomp>
    return [f(y) for y in x]
  File "/config/custom_components/hikvision_axpro/model.py", line 817, in from_dict
    zone = ZoneConfig.from_dict(obj.get("Zone"))
  File "/config/custom_components/hikvision_axpro/model.py", line 660, in from_dict
    detector_type = DetectorType(obj.get("detectorType"))
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'wirelesTriTechDetector' is not a valid DetectorType
```

**Comment by petrleocompel** [comment]
released [v2.0.0-beta12](https://github.com/petrleocompel/hikaxpro_hacs/releases/v2.0.0-beta12)
