### ISSUE TITLE
Error setting up entry Hikvision_axpro

### ISSUE THREAD

**Issue by florianlog** [petrleocompel/hikaxpro_hacs#48]
Hi, @petrleocompel, thank you for this great module that I've installed on several HA without any problems so far. 

On this HA I have an error when activating:

This error is from a custom integration

```
Logger: homeassistant.config_entries
Source: custom_components/hikvision_axpro/model.py:18
Integration: hikvision_axpro
First occurred: 10:40:42 (1 occurrences)
Last logged: 10:40:42

Error setting up entry Hikvision_axpro_192.168.1.51 for hikvision_axpro
Traceback (most recent call last):
   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
     result = await component.async_setup_entry(hass, self)
   File "/config/custom_components/hikvision_axpro/__init__.py", line 105, in async_setup_entry
     await hass.async_add_executor_job(coordinator.init_device)
   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
     result = self.fn(*self.args, **self.kwargs)
   File "/config/custom_components/hikvision_axpro/__init__.py", line 177, in init_device
     self.load_devices()
   File "/config/custom_components/hikvision_axpro/__init__.py", line 181, in load_devices
     devices = self._load_devices()
   File "/config/custom_components/hikvision_axpro/__init__.py", line 194, in _load_devices
     return ZonesConf.from_dict(response.json())
   File "/config/custom_components/hikvision_axpro/model.py", line 834, in from_dict
     list = from_list(ListElement.from_dict, obj.get("List"))
   File "/config/custom_components/hikvision_axpro/model.py", line 29, in from_list
     return [f(y) for y in x]
   File "/config/custom_components/hikvision_axpro/model.py", line 29, in <listcomp>
     return [f(y) for y in x]
   File "/config/custom_components/hikvision_axpro/model.py", line 818, in from_dict
     area = AreaConfig.from_dict(obj.get("Area"))
   File "/config/custom_components/hikvision_axpro/model.py", line 676, in from_dict
     double_knock_enabled = from_bool(obj.get("doubleKnockEnabled"))
   File "/config/custom_components/hikvision_axpro/model.py", line 18, in from_bool
     assert isinstance(x, bool)
AssertionError
```

If there would be a solution to reassemble the AXPRO central

I specify that HA as well as HACS and everything else is up to date

Thanks in advance

Florian

**Comment by petrleocompel** [comment]
released version v2.0.0-beta13
