### ISSUE TITLE
Error setting up entry Hikvision_axpro_######## for hikvision_axpro

### ISSUE THREAD

**Issue by xoferz** [petrleocompel/hikaxpro_hacs#66]
Hi, 

adding hikvision_axpro fails with 'tamperDetector' is not a valid DetectorType

```
2023-08-17 14:11:59.712 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Hikvision_axpro_******* for hikvision_axpro

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)

  File "/config/custom_components/hikvision_axpro/__init__.py", line 105, in async_setup_entry
    await hass.async_add_executor_job(coordinator.init_device)

  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)

  File "/config/custom_components/hikvision_axpro/__init__.py", line 180, in init_device
    self.load_devices()

  File "/config/custom_components/hikvision_axpro/__init__.py", line 217, in load_devices
    devices = self._load_devices()

  File "/config/custom_components/hikvision_axpro/__init__.py", line 230, in _load_devices
    return ZonesConf.from_dict(response.json())

  File "/config/custom_components/hikvision_axpro/model.py", line 928, in from_dict
    list = from_list(ZoneConfListWrap.from_dict, obj.get("List"))

  File "/config/custom_components/hikvision_axpro/model.py", line 29, in from_list
    return [f(y) for y in x]

  File "/config/custom_components/hikvision_axpro/model.py", line 29, in <listcomp>
    return [f(y) for y in x]

  File "/config/custom_components/hikvision_axpro/model.py", line 912, in from_dict
    zone = ZoneConfig.from_dict(obj.get("Zone"))

  File "/config/custom_components/hikvision_axpro/model.py", line 672, in from_dict
    detector_type = DetectorType(obj.get("detectorType"))

  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)

  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc

ValueError: 'tamperDetector' is not a valid DetectorType
```

**Comment by petrleocompel** [comment]
fixed in [v2.1.0-beta7](https://github.com/petrleocompel/hikaxpro_hacs/releases/tag/v2.1.0-beta7)
