### ISSUE TITLE
CrossZoneCfg parsing error

### ISSUE THREAD

**Issue by petrleocompel** [petrleocompel/hikaxpro_hacs#82]
I'm having the same problem using V2.1.0-beta10. 
Can you please help me?? It was working fine until a few months ago.

<img width="972" alt="Captura de pantalla 2024-01-08 a la(s) 19 53 09" src="https://github.com/petrleocompel/hikaxpro_hacs/assets/1308177/fa834966-d49e-406d-aca6-a64459894103">

Here are my logs:
```
Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 7 de enero de 2024, 22:48:41 (4 occurrences)
Last logged: 20:04:37

Error setting up entry Hikvision_axpro_192.168.4.177 for hikvision_axpro
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_axpro/__init__.py", line 107, in async_setup_entry
    await hass.async_add_executor_job(coordinator.init_device)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_axpro/__init__.py", line 185, in init_device
    self.load_devices()
  File "/config/custom_components/hikvision_axpro/__init__.py", line 223, in load_devices
    devices = self._load_devices()
              ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_axpro/__init__.py", line 236, in _load_devices
    return ZonesConf.from_dict(response.json())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_axpro/model.py", line 932, in from_dict
    list = from_list(ZoneConfListWrap.from_dict, obj.get("List"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_axpro/model.py", line 29, in from_list
    return [f(y) for y in x]
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_axpro/model.py", line 29, in <listcomp>
    return [f(y) for y in x]
            ^^^^
  File "/config/custom_components/hikvision_axpro/model.py", line 916, in from_dict
    zone = ZoneConfig.from_dict(obj.get("Zone"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_axpro/model.py", line 725, in from_dict
    cross_zone_cfg = from_union([CrossZoneCFG.from_dict, from_none], obj.get("CrossZoneCfg"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_axpro/model.py", line 43, in from_union
    assert False
AssertionError
```

I'm currently using Home Assistant version 2023.11.2 on HA OS v 11.1. Any assistance or guidance you can provide would be greatly appreciated.

Thank you!

_Originally posted by @jpgalecio in https://github.com/petrleocompel/hikaxpro_hacs/issues/68#issuecomment-1881972213_

**Comment by petrleocompel** [comment]
Fixed in [v2.1.0-beta11](https://github.com/petrleocompel/hikaxpro_hacs/releases/tag/v2.1.0-beta11)
