### ISSUE TITLE
Arming error

### ISSUE THREAD

**Issue by petrleocompel** [petrleocompel/hikaxpro_hacs#97]
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:240
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:31:48 (1 occurrences)
Last logged: 10:31:48

[140061426111680] Unexpected response status code 400 returned with message { "statusCode": 4, "statusString": "Invalid Operation", "subStatusCode": "arming", "errorCode": 1073774621, "errorMsg": "arming" }
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/hikvision_axpro/alarm_control_panel.py", line 127, in async_alarm_arm_away
    await self.coordinator.async_arm_away()
  File "/config/custom_components/hikvision_axpro/__init__.py", line 319, in async_arm_away
    is_success = await self.hass.async_add_executor_job(self.axpro.arm_away, sub_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hikaxpro.py", line 197, in arm_away
    return self._base_json_request(f"http://{self.host}{consts.Endpoints.Alarm_ArmAway.replace('{}', sid)}",
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hikaxpro.py", line 180, in _base_json_request
    raise errors.UnexpectedResponseCodeError(response.status_code, response.text)
errors.errors.UnexpectedResponseCodeError: Unexpected response status code 400 returned with message { "statusCode": 4, "statusString": "Invalid Operation", "subStatusCode": "arming", "errorCode": 1073774621, "errorMsg": "arming" }

```

**Comment by petrleocompel** [comment]
Could be a problem of "open zone" or user not having permission to arm

**Comment by Drealine** [comment]
Hi @petrleocompel 
Having the same issue but with some new cases.
I can arm/disarm but can't switch from home to away in HomeAssistant, it give me the same error

**Comment by petrleocompel** [comment]
@Drealine @PierluigiGreto 

It is not a same issue until you provide logs. 
Arming works in general. I am using it every day. 

You can read the FAQ of dev branch currently. 
https://github.com/petrleocompel/hikaxpro_hacs/tree/dev?tab=readme-ov-file#cannot-arm-my-system-with-ha
It will give you some general help. 
Also if you want me to "focus" on this you need to provide logs. 

This log is from somebody who send it via email and I have no clue who was it.
Also his system was not supporting the endpoint so it seems like dead point.

**Comment by petrleocompel** [comment]
Arming with open/triggered zones is addressed via the new bypass flow in **v3.2.0** (opt-in auto-bypass and arm-with-bypass services). Also confirm Admin (not Installer) account and closed/healthy zones per the FAQ.

Fixed in **v3.2.0**. Please upgrade via HACS (or update the custom component) and reload the integration. Reopen if it still reproduces on 3.2.0.
