### ISSUE TITLE
AX HUB Registration

### ISSUE THREAD

**Issue by PablexXXXX** [petrleocompel/hikaxpro_hacs#98]
Can´t integrate, "UNEXPECTED ERROR" when trying to complete the integration wizard in HA. My panel is DS PHA64 B from the AX HUB series.

**Comment by petrleocompel** [comment]
Please provide logs.

**Comment by plbage** [comment]
Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.hikvision_axpro.config_flow
Source: custom_components/hikvision_axpro/config_flow.py:178
intégration: hikvision_axpro
S'est produit pour la première fois: 18:17:57 (7 occurrences)
Dernier enregistrement: 18:26:41

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/hikvision_axpro/hikax/hikax.py", line 38, in get_session_params
    session_cap = self.parse_session_response(response.text)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_axpro/hikax/hikax.py", line 66, in parse_session_response
    session_cap = SessionLoginCap.SessionLoginCap(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SessionLoginCap.__init__() missing 1 required positional argument: 'session_id_version'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/hikvision_axpro/config_flow.py", line 178, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_axpro/config_flow.py", line 151, in validate_input
    if not await hub.authenticate():
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_axpro/config_flow.py", line 116, in authenticate
    is_connect_success = await self.hass.async_add_executor_job(self.axpro.connect)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_axpro/hikax/hikax.py", line 93, in connect
    params = self.get_session_params()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_axpro/hikax/hikax.py", line 41, in get_session_params
    raise errors.IncorrectResponseContentError()
errors.errors.IncorrectResponseContentError: Response content is not in expected form.

**Comment by petrleocompel** [comment]
@PablexXXXX Any update on this ?

**Comment by fede021** [comment]
I had the same issue finnally make it work with this settings:
Host: 192.168.2.57 (my DS-PWA32-HG Ax Hub IP)
Username: admin
Password: •••••
Use code to disarm: no
NUMBER: yes
Code: 123456 (I put any)
Use code for arming: no
Pull interval from system: 30
Include areas as separate zones for arm/disarm: no
DEPRECATED - Use internal API lib (AXHub): no
Enable debug output: yes

**Comment by petrleocompel** [comment]
Sadly it is not helpful at all. This issue is really old. And i never got logs. Also you can have completely different installation then author.

**Comment by petrleocompel** [comment]
Version of Integration was never mentioned from author.

**Comment by jennifer-mh** [comment]
I was originally ticking all three options at the bottom. Only ticking the last one seemed to make the difference as my login details were correct and I could login via the browser, but I was getting the same 'Unexpected Error' message.
Include areas as separate zones for arm/disarm: no
DEPRECATED - Use internal API lib (AXHub): no
Enable debug output: yes

**Comment by petrleocompel** [comment]
As I wrote before 
> Sadly it is not helpful at all. This issue is really old. And i never got logs. Also you can have completely different installation then author.

@jennifer-mh are you having problems ? any of the logs ? 
Did you follow this ?
![image](https://github.com/user-attachments/assets/dfe5bd14-b68d-48de-a96e-9650c3ff94ee)

**Comment by petrleocompel** [comment]
Any news ? @jennifer-mh

**Comment by petrleocompel** [comment]
Try please with version [v2.3.0](https://github.com/petrleocompel/hikaxpro_hacs/releases/tag/v2.3.0) which prevents usage of installer account.

**Comment by petrleocompel** [comment]
@jennifer-mh @PablexXXXX 
In case of no activity - i will close the issue on end of the week.

**Comment by petrleocompel** [comment]
No activity, Closing as stale
@jennifer-mh @PablexXXXX
